export const RWANDA_REGIONS = [
  { name: 'Gasabo', lat: -1.9441, lng: 30.0820 },
  { name: 'Kicukiro', lat: -1.9976, lng: 30.1200 },
  { name: 'Nyarugenge', lat: -1.9506, lng: 30.0588 },

  { name: 'Burera' },
  { name: 'Gicumbi' },
  { name: 'Gakenke' },
  { name: 'Musanze', lat: -1.4989, lng: 29.6347 },
  { name: 'Rulindo' },

  { name: 'Gisagara' },
  { name: 'Huye', lat: -2.5952, lng: 29.7386 },
  { name: 'Kamonyi' },
  { name: 'Muhanga' },
  { name: 'Nyamagabe' },
  { name: 'Nyaruguru' },
  { name: 'Ruhango' },
  { name: 'Nyanza' },

  { name: 'Karongi' },
  { name: 'Ngororero' },
  { name: 'Nyabihu' },
  { name: 'Nyamasheke' },
  { name: 'Rubavu', lat: -1.6788, lng: 29.2667 },
  { name: 'Rusizi', lat: -2.4844, lng: 28.9053 },
  { name: 'Rutsiro' },

  { name: 'Bugesera' },
  { name: 'Gatsibo' },
  { name: 'Kayonza' },
  { name: 'Kirehe' },
  { name: 'Ngoma' },
  { name: 'Nyagatare' },
  { name: 'Rwamagana' },
];
